#!/usr/bin/env bash
# Launch the pipeline ONCE and let cron drive it to completion across GPU windows
# (nights 18:00-08:00 and weekends), killed sessions and reboots.
#
# Usage: DATA_PATH=... [MODEL=... OPT=lamb EPOCHS=... N_KEYS=... PBATCH=64 RESERVE_GPU_MEM=14 \
#         STAGES="pretrain sign validate detect" MARGIN_MIN=10] bash scripts/launch_supervised.sh [--dry-run]
#
# Everything (checkpoints, signed keys, logs, state) goes to a run folder
#   $CHECKPOINT_BASE/<model>_ImageNet1k_<hash8>/     (CHECKPOINT_BASE=/Data/gaetan.degot/checkpoints)
# where <hash8> is the hash of the full experiment config (`reproduce.sh config`: model,
# optimizer, lr, epochs, keys, budget, pbatch and every fixed hyper-parameter). Same config ->
# same folder (the run resumes); any other config -> another folder, so runs cannot collide.
# Stages are sub-folders: pretrained/, poisons/key_<i>/, validation/. Set OUTPUT_ROOT to
# override the folder by hand. --dry-run only prints the folder name.
#        bash scripts/launch_supervised.sh --install [OUTPUT_ROOT]     # cron entry only, idle until a launch
#        bash scripts/launch_supervised.sh --uninstall                 # remove the cron entry
#
# Installs one line in the user's crontab (every 5 min -> scripts/supervisor.sh) and
# runs a first tick. Progress: tail $OUTPUT_ROOT/supervisor.log, cat $OUTPUT_ROOT/timing.txt
# The crontab lives on THIS machine: if it is reimaged or you log in elsewhere, re-run this.
set -euo pipefail
dry_run=0
case "${1:-}" in
  "") ;;
  --dry-run) dry_run=1 ;;
  --install|--uninstall) ;;   # handled below
  *) echo "ERROR: unknown argument '$1' (expected --dry-run, --install [ROOT] or --uninstall)" >&2; exit 2 ;;
esac
repo="$(cd "$(dirname "$0")/.." && pwd)"
tag="# data-taggants-supervisor"

install_cron() {  # $1 = absolute path of the supervisor.env the cron entry will use
  local line="*/5 * * * * /bin/bash $repo/scripts/supervisor.sh $1 $tag"
  ( (crontab -l 2>/dev/null | grep -vF "$tag") || true; echo "$line" ) | crontab -
  echo "Installed cron entry:"; crontab -l | grep -F "$tag"
}

if [ "${1:-}" = "--install" ]; then
  root="${2:-outputs/timing}"; case "$root" in /*) ;; *) root="$repo/$root" ;; esac
  mkdir -p "$root/state"
  install_cron "$root/supervisor.env"
  echo "Idle until a launch writes $root/supervisor.env (heartbeat: $root/state/heartbeat)"
  exit 0
fi

if [ "${1:-}" = "--uninstall" ]; then
  (crontab -l 2>/dev/null | grep -vF "$tag" || true) | crontab -
  echo "cron entry removed (a running pipeline, if any, keeps going until its deadline)"
  exit 0
fi

: "${DATA_PATH:?Set DATA_PATH}"
: "${STAGES:=pretrain sign validate detect}"
: "${CHECKPOINT_BASE:=/Data/gaetan.degot/checkpoints}"
case "$DATA_PATH" in /*) ;; *) DATA_PATH="$repo/$DATA_PATH" ;; esac
export DATA_PATH

config_text="$(cd "$repo" && bash scripts/reproduce.sh config)"
if [ -z "${OUTPUT_ROOT:-}" ]; then
  model="$(grep -o -- '--model [^ ]*' <<< "$config_text" | head -1 | cut -d' ' -f2)"
  hash8="$(printf '%s\n' "$config_text" | sha256sum | cut -c1-8)"
  OUTPUT_ROOT="$CHECKPOINT_BASE/${model}_ImageNet1k_${hash8}"
fi
case "$OUTPUT_ROOT" in /*) ;; *) OUTPUT_ROOT="$repo/$OUTPUT_ROOT" ;; esac
echo "Run folder: $OUTPUT_ROOT"
if [ "$dry_run" -eq 1 ]; then printf '%s\n' "$config_text"; exit 0; fi

mkdir -p "$OUTPUT_ROOT/state"
if [ -f "$OUTPUT_ROOT/run_config.txt" ] && ! diff -q <(printf '%s\n' "$config_text") "$OUTPUT_ROOT/run_config.txt" >/dev/null; then
  echo "ERROR: $OUTPUT_ROOT already holds a run with a different config (see run_config.txt)" >&2; exit 1
fi
printf '%s\n' "$config_text" > "$OUTPUT_ROOT/run_config.txt"

env_file="$OUTPUT_ROOT/supervisor.env"
{
  echo "# generated by launch_supervised.sh on $(date -Is)"
  echo "REPO=$(printf %q "$repo")"
  for v in OUTPUT_ROOT DATA_PATH STAGES MARGIN_MIN MIN_USEFUL_MIN GPU_BUSY_MB MAX_FAILURES RETRY_DELAY_MIN; do
    [ -n "${!v+x}" ] && echo "$v=$(printf %q "${!v}")"
  done
  for v in MODEL OPT LR EPOCHS WORKERS N_KEYS BUDGET_PER_KEY PBATCH RESERVE_GPU_MEM; do
    [ -n "${!v+x}" ] && echo "export $v=$(printf %q "${!v}")"
  done
  echo "export DATA_PATH OUTPUT_ROOT"
} > "$env_file"

install_cron "$env_file"
rm -f "$OUTPUT_ROOT/state/failures" "$OUTPUT_ROOT/state/last_failure_ts" "$OUTPUT_ROOT/state/last_msg"

bash "$repo/scripts/supervisor.sh" "$env_file"   # first tick right away
echo "Supervisor log: $OUTPUT_ROOT/supervisor.log"
tail -3 "$OUTPUT_ROOT/supervisor.log" 2>/dev/null || true
